version: '3.8'

services:
  web:
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postges
      - POSTGRES_PASSWORD=postges
      - POSTGRES_DB=dev